server:
  port: 8082
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://mongoService:27017/tracks
  jpa:
    hibernate:
      ddl_auto:
        application: create
  application:
    name: track-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetchRegistry: true
    registerWithEureka: true